tools:
  jdk: 8
  maven: 3.5.0

triggers:
  - manual: Run default
flows:
  init:
    - sudo yum -y install gcc mysql-devel ruby-devel rubygems 
    - sudo yum install -y postgresql-devel.x86_64 
    - sudo yum groupinstall 'Development Tools' 
    - sudo yum install libxml2-devel 
    - sudo yum install libxslt-devel
  default:
    - call: versionsCheck
    - call: pr
  pr:
    - call: init
    - echo "Running build for $GITHUB_PR_URL"
    - call: versionsCheck
    #- (name Maven build) mvn clean install
    - (name Maven Wrapper Build) ./mvnw clean package -pl adapter,amq-plugin,antenna,cms-admin,cmsdal,controller,daq,display,inductor,oo-commons,opamp,search,sensor,transistor,transmitter,batch,oneops-admin,db-schema,oneops-model 

  versionsCheck:
    - (name JDK Version) java -version
    - (name Maven version) mvn -v
